
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class AddQuestion extends javax.swing.JFrame {
   int i=1;
   int qno=1;
   int Qno;
    /**
     * Creates new form AddQuestion
     */
    public AddQuestion(Vector v1) {
        initComponents();
         this.lblsub.setText((String)v1.elementAt(0));
          this.lblnoq.setText((String)v1.elementAt(1));
    }

    private AddQuestion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblsub_id = new javax.swing.JLabel();
        lblsub = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblnoq = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQ = new javax.swing.JTextArea();
        lblop = new javax.swing.JLabel();
        txtop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblquestno = new javax.swing.JLabel();
        lblqno = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        lblco = new javax.swing.JLabel();
        txtCorr = new javax.swing.JTextField();
        lblmarks = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(133, 214, 242));
        jPanel1.setLayout(null);

        lblsub_id.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblsub_id.setText("Sub_id");
        jPanel1.add(lblsub_id);
        lblsub_id.setBounds(90, 80, 70, 27);
        jPanel1.add(lblsub);
        lblsub.setBounds(190, 80, 63, 29);

        lblno.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblno.setText("No of questions");
        jPanel1.add(lblno);
        lblno.setBounds(40, 130, 132, 27);
        jPanel1.add(lblnoq);
        lblnoq.setBounds(190, 120, 90, 30);

        lblQ.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblQ.setText("Question");
        jPanel1.add(lblQ);
        lblQ.setBounds(80, 190, 80, 27);

        txtQ.setColumns(20);
        txtQ.setRows(5);
        jScrollPane1.setViewportView(txtQ);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 170, 119, 74);

        lblop.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblop.setText("Options");
        jPanel1.add(lblop);
        lblop.setBounds(100, 270, 80, 27);

        txtop.setText("A.    B.    C.    D.");
        txtop.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), null));
        jPanel1.add(txtop);
        txtop.setBounds(200, 270, 138, 18);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("MAX 4 OPTIONS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 270, 170, 27);

        lblquestno.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblquestno.setText("QNO");
        jPanel1.add(lblquestno);
        lblquestno.setBounds(540, 90, 50, 34);
        jPanel1.add(lblqno);
        lblqno.setBounds(620, 90, 37, 34);

        lbladd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbladd.setText("Add questions");
        jPanel1.add(lbladd);
        lbladd.setBounds(310, 20, 190, 40);

        lblco.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblco.setText("Corr");
        jPanel1.add(lblco);
        lblco.setBounds(110, 330, 70, 27);

        txtCorr.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 255), null));
        jPanel1.add(txtCorr);
        txtCorr.setBounds(200, 330, 74, 18);

        lblmarks.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblmarks.setText("marks");
        jPanel1.add(lblmarks);
        lblmarks.setBounds(100, 370, 70, 27);

        lbl2.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lbl2.setText("2");
        jPanel1.add(lbl2);
        lbl2.setBounds(220, 370, 22, 27);

        btnInsert.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert);
        btnInsert.setBounds(180, 430, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void clear()
 {
      
      txtQ.setText("");
                    txtop.setText("");
                   txtCorr.setText("");
                    
 }
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
ConnectQ cq=new ConnectQ();              // creates a connection with questions collection
        DBCollection dbcq=cq.connectq();
        BasicDBObject bdb1= new BasicDBObject();
        int n1=Integer.parseInt(lblnoq.getText());  // no of questions!
        final JPanel p1=new JPanel();
        final JOptionPane jo=new JOptionPane();
        String sub1=txtCorr.getText();
String sub2="^([A-D])$";  
Boolean f2=sub1.matches(sub2);   
String srn="";

        if(f2)
        {
        
        
        
            Qno=qno+1;              //to start printing from 2,to print from 1 window activated
                                    //NOTE: Qno and qno are different
             if((n1+1)!=qno)             // qno starts with 1  and compares with the no of questions allowed
             {
            if(txtQ.getText().toString().equals(""))
            {
                JOptionPane.showMessageDialog(p1,"Enter question","Information Incomplete",JOptionPane.ERROR_MESSAGE);

                //P3.setVisible(true
                }
                else if(txtop.getText().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(p1,"Enter options","Information Incomplete",JOptionPane.ERROR_MESSAGE);

                }
                else if(txtCorr.getText().toString().equals("") )
                {
                    JOptionPane.showMessageDialog(p1,"Enter correct answer","Information Incomplete",JOptionPane.ERROR_MESSAGE);

                }
                else

                {
                    //System.out.println(n1);
                    bdb1.put("sub_id",lblsub.getText());  //to add a new question
                    srn=""+qno;
                    bdb1.put("sr",srn);
                    bdb1.put("q",txtQ.getText());
                    bdb1.put("opt",txtop.getText());
                    bdb1.put("corr",txtCorr.getText());
                    bdb1.put("marks",lbl2.getText());
                    dbcq.insert(bdb1);
                  //  System.out.println(qno);
                  clear();
                  String s=Integer.toString(Qno);      //to convert Qno to string to be able to display on screen
                    lblqno.setText(s);  
                      
                    qno=qno+1;     //increment qno
                       if((n1+1)==qno)       //to exit as soon as the no of questions are done
                               {
                           
                           JOptionPane.showMessageDialog(p1,"All questions have been inserted","Information Incomplete",JOptionPane.INFORMATION_MESSAGE);
                           
                                this.setVisible(false);
                               
                               }// increment the qno for the next question
                }
          }
             else
             {
                 this.setVisible(false);
             }
        }
        else
        {
         JOptionPane.showMessageDialog(p1,"Correct answer can only be A or B or C or D","Information Incomplete",JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblqno.setText("1");  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblco;
    private javax.swing.JLabel lblmarks;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblnoq;
    private javax.swing.JLabel lblop;
    private javax.swing.JLabel lblqno;
    private javax.swing.JLabel lblquestno;
    private javax.swing.JLabel lblsub;
    private javax.swing.JLabel lblsub_id;
    private javax.swing.JTextField txtCorr;
    private javax.swing.JTextArea txtQ;
    private javax.swing.JTextField txtop;
    // End of variables declaration//GEN-END:variables
}
