
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox<>();
        lblPass = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        lblDept = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(133, 214, 242));
        jPanel1.setLayout(null);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 51, 204), null));
        jPanel1.add(txtName);
        txtName.setBounds(300, 90, 130, 30);

        lblName.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblName.setText("Name");
        jPanel1.add(lblName);
        lblName.setBounds(30, 90, 120, 27);

        lblDesignation.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblDesignation.setText("Designation");
        jPanel1.add(lblDesignation);
        lblDesignation.setBounds(30, 150, 120, 27);

        cmbDesignation.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOD", "Professor" }));
        cmbDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignationActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDesignation);
        cmbDesignation.setBounds(300, 150, 90, 30);

        lblPass.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPass.setText("Password");
        jPanel1.add(lblPass);
        lblPass.setBounds(30, 220, 120, 27);

        pwdPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 204), null));
        jPanel1.add(pwdPass);
        pwdPass.setBounds(300, 220, 130, 30);

        lblDept.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblDept.setText("Department");
        jPanel1.add(lblDept);
        lblDept.setBounds(30, 290, 120, 27);

        cmbDept.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        cmbDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMP", "CEES", "IT", "CIVIL", "MECH", "ENTC" }));
        jPanel1.add(cmbDept);
        cmbDept.setBounds(300, 300, 90, 30);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(135, 440, 100, 23);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(380, 440, 90, 23);

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdmin.setText("Admin Registration");
        jPanel1.add(lblAdmin);
        lblAdmin.setBounds(170, 10, 310, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
ConnectAdmin cad=new ConnectAdmin();
DBCollection dbcad=cad.connectadmin();
        BasicDBObject bdb= new BasicDBObject();
        final JPanel p2=new JPanel();
final JOptionPane jo=new JOptionPane();
        pwdPass.selectAll();
        String name1=txtName.getText();
String name2="^([a-z A-Z]+)$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f=name1.matches(name2); // to ensure than roll no entered is only integer
if(f){
        bdb.put("Name",txtName.getText());
        bdb.put("Password",pwdPass.getSelectedText());
        bdb.put("Designation",cmbDesignation.getSelectedItem());
         bdb.put("Department",cmbDept.getSelectedItem());
        dbcad.insert(bdb);
   JOptionPane.showMessageDialog(p2,"Registered successfully!","Success",JOptionPane.INFORMATION_MESSAGE);   
 this.setVisible(false);
new Admin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed
else
{
    JOptionPane.showMessageDialog(p2,"Name can contain only alphabets !","Information Incomplete",JOptionPane.ERROR_MESSAGE);
}    
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.setVisible(false);
new Admin().setVisible(true);
        


// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDesignationActionPerformed

   
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
