
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        lbladmin = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(133, 214, 242));
        jPanel1.setLayout(null);

        lblUsername.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(250, 170, 110, 27);

        lblPassword.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(250, 240, 100, 27);

        pwdPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 51, 255), null));
        jPanel1.add(pwdPass);
        pwdPass.setBounds(390, 240, 202, 20);

        lbladmin.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lbladmin.setText("Admin");
        jPanel1.add(lbladmin);
        lbladmin.setBounds(390, 170, 125, 22);

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdmin.setText("Admin Login");
        jPanel1.add(lblAdmin);
        lblAdmin.setBounds(230, 10, 149, 30);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(280, 390, 100, 40);

        btnRegister.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(83, 390, 120, 40);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(470, 390, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 130, 200, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
 this.setVisible(false);
                new AdminForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         ConnectAdmin cad=new ConnectAdmin();
DBCollection dbcad=cad.connectadmin();

 int flag=0;
 int flag1=0;
         DBCursor cursor=dbcad.find();
           final JPanel p1=new JPanel();
           final JPanel p2=new JPanel();
         final JOptionPane jo=new JOptionPane();
          String s="";
            pwdPass.selectAll();
        if(pwdPass.getText().equals(""))     //emprty password field. getselected does not work
         {
         //JOptionPane.showMessageDialog(p1,"Enter password","login error",JOptionPane.ERROR_MESSAGE);
         this.setVisible(false);
         new Admin().setVisible(true);
         flag1=1;
         }
           if(flag1==0){
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
              String pwd=(String)obj.get("Password");
              
             
         
                if(pwdPass.getSelectedText().toString().equals(pwd))
         {
                JOptionPane.showMessageDialog(p1,"login successful","login success",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new AdminPage().setVisible(true);
                flag=1;
         }
        
          
        
         
       }
        
        if(flag==0)
        {
            
        JOptionPane.showMessageDialog(p1,"Incorrect Password","login error",JOptionPane.ERROR_MESSAGE);
        //pwdPass.setText("");
        }
           }else{
           
            JOptionPane.showMessageDialog(p1,"ENTER Password","login error",JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
   this.setVisible(false);
   new frmWelcome().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed
      
        
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JPasswordField pwdPass;
    // End of variables declaration//GEN-END:variables
}
