
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class AdminPage extends javax.swing.JFrame {
        //to get number of questions
     //for while counter to insert questions
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        btnDisplay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        P5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblRN = new javax.swing.JLabel();
        txtRN = new javax.swing.JTextField();
        btnOKAY = new javax.swing.JButton();
        P4 = new javax.swing.JPanel();
        lblDelTest = new javax.swing.JLabel();
        btnok1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtsu_id = new javax.swing.JTextField();
        P3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        lblUpdate = new javax.swing.JLabel();
        lblsr = new javax.swing.JLabel();
        lblq = new javax.swing.JLabel();
        lblopt = new javax.swing.JLabel();
        lblcorr = new javax.swing.JLabel();
        lblmarks = new javax.swing.JLabel();
        txtsr = new javax.swing.JTextField();
        txtq = new javax.swing.JTextField();
        txtopt = new javax.swing.JTextField();
        txtcorr = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblM = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        lblSubject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblsid = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        lblqu = new javax.swing.JLabel();
        txtNoqu = new javax.swing.JTextField();
        rdbShowA = new javax.swing.JRadioButton();
        rdbStuDel = new javax.swing.JRadioButton();
        rdbDelTest = new javax.swing.JRadioButton();
        rdbAdd = new javax.swing.JRadioButton();
        rdbRec = new javax.swing.JRadioButton();
        rdbUpdate = new javax.swing.JRadioButton();
        btnGO = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(133, 214, 242));
        jPanel1.setLayout(null);

        P1.setBackground(new java.awt.Color(133, 214, 242));
        P1.setLayout(null);

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Roll No.", "DOB", "Gender", "Parent's Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetails);

        P1.add(jScrollPane2);
        jScrollPane2.setBounds(22, 65, 520, 95);

        btnDisplay.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        P1.add(btnDisplay);
        btnDisplay.setBounds(46, 171, 110, 30);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        P1.add(btnBack);
        btnBack.setBounds(190, 170, 80, 30);

        jPanel1.add(P1);
        P1.setBounds(9, 200, 560, 234);

        P5.setBackground(new java.awt.Color(133, 214, 242));
        P5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel3.setText("Delete a Student Record");
        P5.add(jLabel3);
        jLabel3.setBounds(27, 11, 210, 27);

        lblRN.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblRN.setText("Enter Roll No");
        P5.add(lblRN);
        lblRN.setBounds(17, 60, 130, 29);

        txtRN.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P5.add(txtRN);
        txtRN.setBounds(170, 60, 78, 29);

        btnOKAY.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnOKAY.setText("OK");
        btnOKAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKAYActionPerformed(evt);
            }
        });
        P5.add(btnOKAY);
        btnOKAY.setBounds(110, 113, 60, 30);

        jPanel1.add(P5);
        P5.setBounds(630, 410, 300, 170);

        P4.setBackground(new java.awt.Color(133, 214, 242));
        P4.setLayout(null);

        lblDelTest.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblDelTest.setText("Delete Test");
        P4.add(lblDelTest);
        lblDelTest.setBounds(80, 10, 120, 26);

        btnok1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnok1.setText("OK");
        btnok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnok1ActionPerformed(evt);
            }
        });
        P4.add(btnok1);
        btnok1.setBounds(107, 130, 70, 23);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel2.setText("Enter Subject ID");
        P4.add(jLabel2);
        jLabel2.setBounds(10, 70, 150, 38);

        txtsu_id.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P4.add(txtsu_id);
        txtsu_id.setBounds(190, 70, 80, 35);

        jPanel1.add(P4);
        P4.setBounds(9, 10, 310, 180);

        P3.setBackground(new java.awt.Color(133, 214, 242));
        P3.setLayout(null);

        btnUpdate.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        P3.add(btnUpdate);
        btnUpdate.setBounds(40, 250, 80, 40);

        lblUpdate.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblUpdate.setText("Update Quiz");
        P3.add(lblUpdate);
        lblUpdate.setBounds(100, 10, 120, 27);

        lblsr.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblsr.setText("sr");
        P3.add(lblsr);
        lblsr.setBounds(47, 72, 40, 27);

        lblq.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblq.setText("q");
        P3.add(lblq);
        lblq.setBounds(50, 100, 28, 27);

        lblopt.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblopt.setText("opt");
        P3.add(lblopt);
        lblopt.setBounds(50, 140, 28, 27);

        lblcorr.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblcorr.setText("corr");
        P3.add(lblcorr);
        lblcorr.setBounds(50, 170, 50, 27);

        lblmarks.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblmarks.setText("marks");
        P3.add(lblmarks);
        lblmarks.setBounds(40, 200, 54, 27);
        P3.add(txtsr);
        txtsr.setBounds(180, 80, 83, 20);

        txtq.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P3.add(txtq);
        txtq.setBounds(180, 110, 112, 18);

        txtopt.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoptActionPerformed(evt);
            }
        });
        P3.add(txtopt);
        txtopt.setBounds(180, 140, 112, 18);

        txtcorr.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P3.add(txtcorr);
        txtcorr.setBounds(180, 170, 89, 18);

        btnBack1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        P3.add(btnBack1);
        btnBack1.setBounds(190, 250, 80, 40);

        lblid.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblid.setText("sub_id");
        P3.add(lblid);
        lblid.setBounds(47, 46, 57, 27);

        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P3.add(txtid);
        txtid.setBounds(180, 50, 68, 18);

        lblM.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblM.setText("2");
        P3.add(lblM);
        lblM.setBounds(190, 204, 58, 20);

        jPanel1.add(P3);
        P3.setBounds(680, 50, 311, 320);

        P2.setBackground(new java.awt.Color(133, 214, 242));
        P2.setLayout(null);

        lblSubject.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblSubject.setText("Add Subject");
        P2.add(lblSubject);
        lblSubject.setBounds(290, 40, 110, 27);

        txtSubject.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        P2.add(txtSubject);
        txtSubject.setBounds(410, 40, 80, 18);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        P2.add(btnSubmit);
        btnSubmit.setBounds(80, 130, 90, 30);

        lblsid.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblsid.setText("Add Subject id");
        P2.add(lblsid);
        lblsid.setBounds(21, 34, 130, 27);

        txtsid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P2.add(txtsid);
        txtsid.setBounds(160, 30, 50, 30);

        lblqu.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblqu.setText("Enter No of Questions:");
        P2.add(lblqu);
        lblqu.setBounds(26, 87, 194, 27);

        txtNoqu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P2.add(txtNoqu);
        txtNoqu.setBounds(230, 90, 40, 20);

        jPanel1.add(P2);
        P2.setBounds(40, 430, 500, 180);

        buttonGroup1.add(rdbShowA);
        rdbShowA.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbShowA.setText("Show Analysis");
        jPanel1.add(rdbShowA);
        rdbShowA.setBounds(1180, 120, 170, 31);

        buttonGroup1.add(rdbStuDel);
        rdbStuDel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbStuDel.setText("Delete a Student Record");
        jPanel1.add(rdbStuDel);
        rdbStuDel.setBounds(1180, 170, 227, 31);

        buttonGroup1.add(rdbDelTest);
        rdbDelTest.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbDelTest.setText("Delete a Test");
        rdbDelTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDelTestActionPerformed(evt);
            }
        });
        jPanel1.add(rdbDelTest);
        rdbDelTest.setBounds(1180, 220, 133, 31);

        buttonGroup1.add(rdbAdd);
        rdbAdd.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbAdd.setText("Add Subject");
        jPanel1.add(rdbAdd);
        rdbAdd.setBounds(1180, 270, 129, 30);

        buttonGroup1.add(rdbRec);
        rdbRec.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbRec.setText("Student Records");
        jPanel1.add(rdbRec);
        rdbRec.setBounds(1180, 310, 180, 30);

        buttonGroup1.add(rdbUpdate);
        rdbUpdate.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        rdbUpdate.setText("Update");
        rdbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(rdbUpdate);
        rdbUpdate.setBounds(1180, 360, 90, 31);

        btnGO.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnGO.setText("GO");
        btnGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGOActionPerformed(evt);
            }
        });
        jPanel1.add(btnGO);
        btnGO.setBounds(1220, 430, 51, 30);

        btnLogOut.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(1190, 70, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Page");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(452, 20, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
         Connect j=new Connect();
        DBCollection dbc=j.connect();
        BasicDBObject bdb= new BasicDBObject();
        P2.setVisible(false);
        P3.setVisible(false);
        String[] colNames={"Name","RollNo","DOB","Gender","Parent's Name","Email"};
        DefaultTableModel dtm=new DefaultTableModel(colNames,0);
        DBCursor cursor=dbc.find();
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
           
            String name=(String)obj.get("Name");
             String rno=(String)obj.get("RollNo");
            String dob=(String)obj.get("DOB");
            String gender=(String)obj.get("Gender");
            String pname=(String)obj.get("Parent's Name");
            String email=(String)obj.get("Email");
         
            
         dtm.addRow(new Object[]{name,rno,dob,gender,pname,email});
         tblDetails.setModel(dtm);
        }
        
                         
    }//GEN-LAST:event_btnDisplayActionPerformed

    public void clear()
{
     txtid.setText("");
     txtsr.setText("");
     txtq.setText("");
     txtopt.setText("");
     txtcorr.setText("");
     
}
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
        BasicDBObject bdb1= new BasicDBObject();
       P1.setVisible(false);
       P2.setVisible(false);
         final JPanel p1=new JPanel();     
         final JOptionPane jo=new JOptionPane();
          final JPanel p2=new JPanel();
int flag=0;
   String r = txtsr.getText(); //takes sr from Admin
   String subid=txtid.getText(); //takes subject id from Admin
    String sub1=txtcorr.getText();
String sub2="^([A-D])$";  
Boolean f2=sub1.matches(sub2);  
         
    if(txtid.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Subject id","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             
             //P3.setVisible(true); 
            
           
        }
        else if(txtsr.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Serial No.","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             clear();
               
        }
        else if(txtq.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Question","Information Incomplete",JOptionPane.ERROR_MESSAGE);
            clear();
        }
        else if(txtopt.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Options","Information Incomplete",JOptionPane.ERROR_MESSAGE);
                clear();
        }    
         else if(txtcorr.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Correct Answer","Information Incomplete",JOptionPane.ERROR_MESSAGE);
               clear();
        }
          else if(!f2)
        {
             JOptionPane.showMessageDialog(p1,"Enter Correct Answer","Information Incomplete",JOptionPane.ERROR_MESSAGE);
              
        }
          else if(f2)
        {
      DBCursor cursor=dbcq.find();   //Cursor starts finding from Collection Questions
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
            if(obj.get("sr").toString().equals("") || (obj.get("sub_id").toString().equals("")))
           
            {
                 JOptionPane.showMessageDialog(p2,"enter valid data","error",JOptionPane.ERROR_MESSAGE);
                break;
            }
            else{
            String rno=(String) (obj.get("sr"));  //takes each "sr" from Database to Compare
            String s_id=(String) (obj.get("sub_id")); //takes each "sub_id" from Database to Compare
           //     System.out.println(rno);
            //     System.out.println(s_id);
            if(r.equals(rno) && subid.equals(s_id)){
           
 /*BasicDBObject bdb2= new BasicDBObject().append(subid,new BasicDBObject().append("sr",rno));// for that particular subid entered by user and that for that particular "sr" from the database! 
                    
         flag = 1;  
        bdb1.put("sub_id",txtid.getText());  
        bdb1.put("sr",txtsr.getText());
        bdb1.put("q",txtq.getText());
        bdb1.put("opt",txtopt.getText());
          bdb1.put("corr",txtcorr.getText());
           bdb1.put("marks",lblM.getText());
           
       dbcq.update(bdb2,bdb1); //puts new document bdb1 into document bdb2 */
       System.out.println(rno);
                System.out.println(s_id);
       BasicDBObject bdb = new BasicDBObject().append("sub_id",s_id);
       if(r.equals(rno))
       {
     BasicDBObject bdb2 = new BasicDBObject();
flag = 1;  
        bdb2.put("sub_id",txtid.getText());  
        bdb2.put("sr",txtsr.getText());
        bdb2.put("q",txtq.getText());
        bdb2.put("opt",txtopt.getText());
          bdb2.put("corr",txtcorr.getText());
         // String m=lblM.getText();
         
           bdb2.put("marks",2); // so that we input marks as an integer!
//newDocument.put("clients", 110);


dbcq.update(bdb,bdb2);  
       
       
         JOptionPane.showMessageDialog(p2,"Updated","Success",JOptionPane.INFORMATION_MESSAGE);
         break;
       }
            }
           
        }
        }
        if(flag==0)
        {
              JOptionPane.showMessageDialog(p1,"NOT FOUND","error",JOptionPane.ERROR_MESSAGE);
        }
   clear();
   
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed
    
         
    
    

    
    private void txtoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoptActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

ConnectSub sub=new ConnectSub();
DBCollection dbcsub=sub.connectsub();
DBCursor cursor=dbcsub.find();  
 BasicDBObject bdb= new BasicDBObject();
 int flag=0;
 int flag1=0;
 final JPanel p1=new JPanel();     
         final JOptionPane jo=new JOptionPane();
  String sid1=txtsid.getText();
String sid2="^([a-zA-Z0-9]+)$"; //  the subject id should only be a alphabet or no
Boolean f1=sid1.matches(sid2);      
  String sub1=txtSubject.getText();
String sub2="^([a-zA-Z0-9]+)$";  
Boolean f2=sub1.matches(sub2);          
 String rl1=txtNoqu.getText();
String rl2="^([0-9]+)$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f=rl1.matches(rl2);        
         
if(f2 && f1 && f)
{
         
P1.setVisible(false);
P3.setVisible(false);
if(txtsid.getText().toString().equals("") || txtSubject.getText().toString().equals("")|| txtNoqu.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter subject details properly","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             flag1=1;
             P2.setVisible(false);
            
        }

  
      while(cursor.hasNext())            
           { 
             DBObject obj1=cursor.next();  //to search from studinfo
             String SI=(String)obj1.get("S_id");
               if(txtsid.getText().equals(SI))
               {
                    JOptionPane.showMessageDialog(p1,"Subject id exists","Information Incomplete",JOptionPane.ERROR_MESSAGE);
                     P2.setVisible(false);
                     flag=1;
                     break;
                    
                     
               }
           }
      if(flag==0)
      {
     int n=Integer.parseInt(txtNoqu.getText());
     bdb.put("Name",txtSubject.getText());
     bdb.put("S_id",txtsid.getText());
     dbcsub.insert(bdb);
       JOptionPane.showMessageDialog(p1,"Subject and ID Added","Success",JOptionPane.INFORMATION_MESSAGE);
          //System.out.println("in");
          Vector v1=new Vector();
             v1.add(txtsid.getText());
                  v1.add(txtNoqu.getText());
                 new AddQuestion(v1).setVisible(true);
    
     
       

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed
 
  }
  else if((flag1!=1 && !f) || !f1 || !f2)
  {
        JOptionPane.showMessageDialog(p1,"Enter Subject details properly","Success",JOptionPane.ERROR_MESSAGE);
        
        //P2.setVisible(false);
   
    txtSubject.setText("");
    txtsid.setText("");
    txtNoqu.setText("");
    
    }}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    P1.setVisible(false);
    P2.setVisible(false);
    P3.setVisible(false);
     P4.setVisible(false);
     P5.setVisible(false);
   //  P7.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void rdbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbUpdateActionPerformed

    private void btnGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGOActionPerformed
      P1.setVisible(false);
    P2.setVisible(false);
    P3.setVisible(false);
     P4.setVisible(false);
     P5.setVisible(false);
        
        
     if(rdbAdd.isSelected()){
        P2.setVisible(true);  
     }
     if(rdbRec.isSelected()){
        P1.setVisible(true);  
     }
     if(rdbUpdate.isSelected()){
        P3.setVisible(true);  
     }
     if(rdbDelTest.isSelected()){
        P4.setVisible(true);  
     }
      if(rdbStuDel.isSelected()){
        P5.setVisible(true);  
     } if(rdbShowA.isSelected()){
         this.setVisible(false);
        new Analysis().setVisible(true);  
     }
     
     

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGOActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
P1.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
P3.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
  
        this.setVisible(false);
        new Admin().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnok1ActionPerformed
         ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
      ConnectSub csub=new ConnectSub();
DBCollection dbcsub=csub.connectsub();
DBCursor cursor=dbcq.find(); //cursor for Questions cllection
DBCursor cursor1=dbcsub.find(); //cursor for Subjects cllection
final JPanel p2=new JPanel();
final JOptionPane jo=new JOptionPane();
int flag=0;
int flag1=0;
 BasicDBObject bdb = new BasicDBObject();
 BasicDBObject bdb1 = new BasicDBObject();
 String id=txtsu_id.getText();
 
 if(txtsu_id.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p2,"Enter valid id","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             P4.setVisible(false);
             
        }
 
while(cursor.hasNext())       // to delete from the Questions Collection     
           { 
             DBObject obj=cursor.next();  //to search from Questions
             String sub=(String)obj.get("sub_id");  //from the collection of questions
             if(txtsu_id.getText().equals(sub))
             {
                
bdb.put("sub_id",id);
dbcq.remove(bdb);
flag=1;                                
        
              
             }
           }


while(cursor1.hasNext())        // to delete from the Subjects Collection     
           { 
             DBObject obj1=cursor1.next();  //to search from Subjects
             String sub1=(String)obj1.get("S_id");  //from the collection of Subjects
             if(txtsu_id.getText().equals(sub1))
             {
                
bdb1.put("S_id",id);
dbcsub.remove(bdb1);
                 System.out.println(flag1);
                 System.out.println(id);
flag1=1;     
                 System.out.println(flag1);
break;                
        
              
             }
           }
if(flag==1 && flag1==1)
{
 JOptionPane.showMessageDialog(p2,"Test is Deleted!","Information Incomplete",JOptionPane.INFORMATION_MESSAGE);
}
else
   JOptionPane.showMessageDialog(p2,"Test is not Deleted!","Information Incomplete",JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_btnok1ActionPerformed
    
    private void rdbDelTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDelTestActionPerformed
       
    }//GEN-LAST:event_rdbDelTestActionPerformed

    private void btnOKAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKAYActionPerformed
         Connect c=new Connect(); //connection to studinfo
DBCollection dbc=c.connect();
DBCursor cursor=dbc.find();    
final JPanel p2=new JPanel();
final JPanel p1=new JPanel();
final JOptionPane jo=new JOptionPane();
int flag=0;
int flag1=0;
 BasicDBObject bdb = new BasicDBObject();
 String RN=txtRN.getText();  // getting the roll no entered by admin

String rl2="^([0-9]+)$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f=RN.matches(rl2);        
 
 if(f)
 {
 if(txtRN.getText().toString().equals("")) // in case admin doesnt enter anything
        {
             P5.setVisible(false);
             JOptionPane.showMessageDialog(p1,"Enter Roll no","Information Incomplete",JOptionPane.ERROR_MESSAGE);
            
             P5.setVisible(true);
        }
while(cursor.hasNext())            
           { 
             DBObject obj=cursor.next();  //to search from studinfo
             String rn=(String)obj.get("RollNo");  //from the collection of studinfo
             if(RN.equals(rn)) 
             {
                
bdb.put("RollNo",RN); // Puts query in a BasicDBObject. In this case, all details of that roll no are deleted.
dbc.remove(bdb); // DELETE OPERATION 
flag=1;                
                 
        
              
             }
           }

ConnectA ca=new ConnectA();       // same procedure for deletion from analysis!
DBCollection dbca=ca.connecta();
DBCursor cursor1=dbca.find();    


 BasicDBObject bdb1 = new BasicDBObject();

while(cursor1.hasNext())            
           { 
             DBObject obj1=cursor1.next();  //to search from studinfo
             String rn1=(String)obj1.get("RollNo");  //from the collection of studinfo
             if(RN.equals(rn1))
             {
                
bdb1.put("RollNo",RN);
dbca.remove(bdb1);
flag1=1;                
                 
        
              
             }
           }
 


 }
 txtRN.setText("");       // to clear the input
if(flag==1 || flag1==1)
{
 JOptionPane.showMessageDialog(p2,"Student Record is Deleted!","Information Incomplete",JOptionPane.INFORMATION_MESSAGE);
}
else
   JOptionPane.showMessageDialog(p2,"Student Record is not Deleted!","Information Incomplete",JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_btnOKAYActionPerformed
/**
    **
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JPanel P4;
    private javax.swing.JPanel P5;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnGO;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOKAY;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnok1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDelTest;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblRN;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblcorr;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmarks;
    private javax.swing.JLabel lblopt;
    private javax.swing.JLabel lblq;
    private javax.swing.JLabel lblqu;
    private javax.swing.JLabel lblsid;
    private javax.swing.JLabel lblsr;
    private javax.swing.JRadioButton rdbAdd;
    private javax.swing.JRadioButton rdbDelTest;
    private javax.swing.JRadioButton rdbRec;
    private javax.swing.JRadioButton rdbShowA;
    private javax.swing.JRadioButton rdbStuDel;
    private javax.swing.JRadioButton rdbUpdate;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtNoqu;
    private javax.swing.JTextField txtRN;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtcorr;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtopt;
    private javax.swing.JTextField txtq;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsr;
    private javax.swing.JTextField txtsu_id;
    // End of variables declaration//GEN-END:variables
}
