
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class Analysis extends javax.swing.JFrame {
             int sum=0;
             int count=0;
    /**
     * Creates new form Analysis
     */
    public Analysis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P2 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        P1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarks = new javax.swing.JTable();
        btnGetAvg = new javax.swing.JButton();
        lblAvg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 240, 65));
        jPanel1.setLayout(null);

        P2.setBackground(new java.awt.Color(240, 240, 65));
        P2.setLayout(null);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        P2.add(btnSubmit);
        btnSubmit.setBounds(100, 210, 87, 23);

        lblSub.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblSub.setText("Enter Subject id:");
        P2.add(lblSub);
        lblSub.setBounds(10, 100, 170, 27);

        txtSub.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 204, 0), null));
        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });
        P2.add(txtSub);
        txtSub.setBounds(190, 100, 150, 30);

        jPanel1.add(P2);
        P2.setBounds(0, 10, 380, 450);

        P1.setBackground(new java.awt.Color(240, 240, 65));
        P1.setLayout(null);

        tblMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RollNo", "Name", "sub_id", "Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarks);

        P1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 303, 190);

        btnGetAvg.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnGetAvg.setText("Get Average");
        btnGetAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAvgActionPerformed(evt);
            }
        });
        P1.add(btnGetAvg);
        btnGetAvg.setBounds(100, 380, 110, 30);
        P1.add(lblAvg);
        lblAvg.setBounds(150, 440, 81, 45);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel1.setText("Average  =");
        P1.add(jLabel1);
        jLabel1.setBounds(30, 450, 99, 45);

        jPanel1.add(P1);
        P1.setBounds(390, 0, 350, 550);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(260, 490, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
     ConnectA cq=new ConnectA();              // creates a connection with questions collection
        DBCollection dbca=cq.connecta();  
        String s=txtSub.getText();
        int m;
        int flag=0;
        int flag1=0;
        final JPanel p1=new JPanel();
final JOptionPane jo=new JOptionPane();
 if(txtSub.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter valid id","Information Incomplete",JOptionPane.ERROR_MESSAGE);
              txtSub.setText(""); // to clear
               flag1=1;
             
        }                 
         String[] colNames={"RollNo","Name","sub_id","Marks"};
        DefaultTableModel dtm=new DefaultTableModel(colNames,0);
        DBCursor cursor=dbca.find();
         /* if(s.toString().equals(""))
          {
             flag1=1;
            
          }*/
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
                 String str=(String)obj.get("sub_id");
                  if(s.equals(str)){
                      P1.setVisible(true);
                      System.out.println("in");
           //String marks=(String)obj.get("Marks");
              String sub=(String)obj.get("sub_id");
            String rno=(String)obj.get("RollNo");
            String name=(String)obj.get("Name");
           
           //m=Integer.valueOf(obj.get("Marks"));
           
           Integer marks=(Integer)obj.get("Marks");

            
         dtm.addRow(new Object[]{rno,name,sub,marks});
         tblMarks.setModel(dtm);
    flag=1;
         
        }
        }
        if(flag==0 || flag1==1){
        JOptionPane.showMessageDialog(p1,"Not found","Not found",JOptionPane.ERROR_MESSAGE);
             this.setVisible(false);
             new AdminPage().setVisible(true);
        
        }

   //txtSub.setText(""); // to clear
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
P1.setVisible(false); 
P2.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnGetAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAvgActionPerformed
ConnectA cq=new ConnectA();              // creates a connection with questions collection
        DBCollection dbca=cq.connecta();  
        DBCursor cursor=dbca.find();
         
         final JPanel p1=new JPanel();
final JOptionPane jo=new JOptionPane();
         float avg;
         int flag=0;
         String s=txtSub.getText();
         System.out.println(s);
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
            
            String str=(String)obj.get("sub_id");
             System.out.println(str);
                if(s.equals(str))
                {
                    System.out.println("in IF");
                   Integer marks=(Integer)obj.get("Marks");
                    System.out.println(marks);
                   sum=marks+sum;
                   count++;
                  
                   flag=1;
                   
                   }
        
        }     System.out.println(count);
        System.out.println(sum);
            avg=sum/count;
            System.out.println(avg);
            String a=""+avg;
            lblAvg.setText(a);
           
            P2.setVisible(false); 
             /*  if(avg<15)
               {
               
               JOptionPane.showMessageDialog(p1,"Poor performance","Analysis",JOptionPane.ERROR_MESSAGE);
               
               }
               else if(avg>25)
               {
               
                JOptionPane.showMessageDialog(p1,"Good performance","Analysis",JOptionPane.INFORMATION_MESSAGE);
                 
               }*/
            
            if(flag==0)
            {
            
               JOptionPane.showMessageDialog(p1,"Not found","Not found",JOptionPane.ERROR_MESSAGE);
            }
      //lblAvg.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetAvgActionPerformed

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.setVisible(false);
new AdminPage().setVisible(true);// TODO add         // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetAvg;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblSub;
    private javax.swing.JTable tblMarks;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables
}
