
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class StudentReg extends javax.swing.JFrame {

    /**
     * Creates new form StudentReg
     */
    public StudentReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtRoll = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        JCalDOB = new com.toedter.calendar.JDateChooser();
        txtemail = new javax.swing.JTextField();
        rdbFemale = new javax.swing.JRadioButton();
        rdbMale = new javax.swing.JRadioButton();
        txtPName = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblStuReg = new javax.swing.JLabel();
        lblRoll = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblGen = new javax.swing.JLabel();
        lblPName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(184, 165, 202));
        jPanel1.setLayout(null);

        txtRoll.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 204), null));
        txtRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollActionPerformed(evt);
            }
        });
        jPanel1.add(txtRoll);
        txtRoll.setBounds(330, 60, 150, 30);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        jPanel1.add(txtName);
        txtName.setBounds(330, 110, 150, 30);

        JCalDOB.setMaxSelectableDate(new java.util.Date(978291071000L));
        JCalDOB.setMinSelectableDate(new java.util.Date(-16129000L));
        jPanel1.add(JCalDOB);
        JCalDOB.setBounds(330, 170, 150, 30);

        txtemail.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        jPanel1.add(txtemail);
        txtemail.setBounds(330, 230, 153, 30);

        rdbFemale.setBackground(new java.awt.Color(184, 165, 202));
        buttonGroup1.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        rdbFemale.setText("female");
        rdbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdbFemale);
        rdbFemale.setBounds(400, 300, 90, 23);

        rdbMale.setBackground(new java.awt.Color(184, 165, 202));
        buttonGroup1.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdbMale);
        rdbMale.setBounds(330, 300, 59, 25);

        txtPName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        txtPName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtPName);
        txtPName.setBounds(350, 360, 106, 30);

        pwdPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        jPanel1.add(pwdPass);
        pwdPass.setBounds(350, 430, 120, 30);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(310, 500, 90, 23);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(200, 500, 90, 23);

        lblStuReg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStuReg.setText("Student Registration");
        jPanel1.add(lblStuReg);
        lblStuReg.setBounds(174, 11, 247, 29);

        lblRoll.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblRoll.setText("RollNo");
        jPanel1.add(lblRoll);
        lblRoll.setBounds(70, 60, 70, 25);

        lblName.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblName.setText("Name");
        jPanel1.add(lblName);
        lblName.setBounds(70, 110, 126, 30);

        lblDOB.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblDOB.setText("DOB");
        jPanel1.add(lblDOB);
        lblDOB.setBounds(70, 180, 126, 30);

        lblemail.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblemail.setText("Email ID");
        jPanel1.add(lblemail);
        lblemail.setBounds(70, 230, 110, 40);

        lblGen.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblGen.setText("Gender");
        jPanel1.add(lblGen);
        lblGen.setBounds(70, 300, 126, 30);

        lblPName.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPName.setText("Parent's Name");
        jPanel1.add(lblPName);
        lblPName.setBounds(70, 360, 140, 40);

        lblPass.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPass.setText("Password");
        jPanel1.add(lblPass);
        lblPass.setBounds(70, 440, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaleActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Connect c=new Connect();
DBCollection dbc=c.connect();
DBCursor cursor=dbc.find();    
final JPanel p2=new JPanel();
final JOptionPane jo=new JOptionPane();
int flag=0;

String rl1=txtRoll.getText();
String rl2="^[1-9]+([0-9])*([0-9])*$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f=rl1.matches(rl2); // to ensure than roll no entered is only integer


String emailID = txtemail.getText();
String emailRE = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$" ;


Boolean f1 = emailID.matches(emailRE);





if(f && f1)
{ 
while(cursor.hasNext())            
           { 
             DBObject obj1=cursor.next();  //to search from studinfo
             String R=(String)obj1.get("RollNo");  //from the collection of studinfo
             if(txtRoll.getText().equals(R))
             {
              flag=1;
              JOptionPane.showMessageDialog(p2,"Roll No already exists!","Information Incomplete",JOptionPane.ERROR_MESSAGE);
              break;
             }
             
           }
           if(flag==0)
           {
        java.util.Date d=JCalDOB.getDate();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(JCalDOB.getDate());
        String gender;
        
        final JPanel p1=new JPanel();     
         
        if(rdbMale.isSelected())
           gender=rdbMale.getText();
        else
            gender=rdbFemale.getText();
        
        BasicDBObject bdb= new BasicDBObject();
        pwdPass.selectAll();
        bdb.put("RollNo",txtRoll.getText());
        bdb.put("Name",txtName.getText());
        bdb.put("DOB",date);
        bdb.put("Gender",gender);
        bdb.put("Parent's Name",txtPName.getText());
         bdb.put("Password",pwdPass.getSelectedText());
        bdb.put("Email",txtemail.getText());
        if(txtRoll.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Roll no","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             this.setVisible(false);
             new StudentReg().setVisible(true);
        }
        else if(txtName.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Name","Information Incomplete",JOptionPane.ERROR_MESSAGE);
              this.setVisible(false);
               new StudentReg().setVisible(true);
        }
        else if(rdbMale.isSelected()==false && rdbFemale.isSelected()==false)
        {
             JOptionPane.showMessageDialog(p1,"Select gender","Information Incomplete",JOptionPane.ERROR_MESSAGE);
              this.setVisible(false);
               new StudentReg().setVisible(true);
        }
        else if(txtPName.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Parents's name","Information Incomplete",JOptionPane.ERROR_MESSAGE);
                 this.setVisible(false);
               new StudentReg().setVisible(true);
        }
          else if(pwdPass.getSelectedText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Password","Information Incomplete",JOptionPane.ERROR_MESSAGE);
                 this.setVisible(false);
               new StudentReg().setVisible(true);
        }
        else{
        dbc.insert(bdb);
        new Student().setVisible(true); //only if all the reocrds are present and valid, go to student login page
        }
this.setVisible(false);
           }
  /*  Vector v=new Vector();
    String G="";
    pwdPass.selectAll();
                  v.add(txtRoll.getText());
                  v.add(txtName.getText());
                  v.add(txtPName.getText());
                  if(rdbMale.isSelected())
                      G=rdbMale.getText();
                  else
                       G=rdbFemale.getText();
                  v.add(G);
                  String D=sdf.format(JcalDOB.getDate());
                  v.add(D);
                  v.add(pwdPass.getSelectedText()); */
                  //  new Test(v).setVisible(false);



    }//GEN-LAST:event_btnSubmitActionPerformed
else if(!f){
    JOptionPane.showMessageDialog(p2,"enter valid roll no!","Information Incomplete",JOptionPane.ERROR_MESSAGE);
    }
else if(!f1){
    JOptionPane.showMessageDialog(p2,"enter valid email id!","Information Incomplete",JOptionPane.ERROR_MESSAGE);
    }   
    }
    private void txtPNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNameActionPerformed

    private void rdbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFemaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.setVisible(false);
new Student().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JCalDOB;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JLabel lblStuReg;
    private javax.swing.JLabel lblemail;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtRoll;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
