
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pwdPass = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRoll = new javax.swing.JLabel();
        txtRoll = new javax.swing.JTextField();
        lblStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(184, 165, 202));
        jPanel2.setLayout(null);

        btnLogin.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(290, 430, 77, 23);

        btnSignup.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSignup.setText("SignUp");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignup);
        btnSignup.setBounds(110, 430, 87, 23);

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(500, 430, 69, 23);

        pwdPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        pwdPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPassActionPerformed(evt);
            }
        });
        jPanel2.add(pwdPass);
        pwdPass.setBounds(370, 300, 130, 30);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        jPanel2.add(txtName);
        txtName.setBounds(370, 190, 130, 30);

        lblPass.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPass.setText("Password");
        jPanel2.add(lblPass);
        lblPass.setBounds(170, 300, 90, 40);

        lblName.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblName.setText("Name");
        jPanel2.add(lblName);
        lblName.setBounds(170, 180, 70, 30);

        lblRoll.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblRoll.setText("RollNo");
        jPanel2.add(lblRoll);
        lblRoll.setBounds(170, 80, 60, 27);

        txtRoll.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), null));
        txtRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollActionPerformed(evt);
            }
        });
        jPanel2.add(txtRoll);
        txtRoll.setBounds(370, 80, 130, 30);

        lblStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStudent.setText("Student Login");
        jPanel2.add(lblStudent);
        lblStudent.setBounds(263, 11, 167, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
this.setVisible(false);  
 new StudentReg().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
 Connect c=new Connect();
DBCollection dbc=c.connect();
final JPanel p1=new JPanel();
           final JPanel p2=new JPanel();
         final JOptionPane jo=new JOptionPane();
String name1=txtName.getText();
  String s="";
String name2="^([a-z A-Z]+)$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f=name1.matches(name2); // to ensure than roll no entered is only integer
 String r1=txtRoll.getText();
String r2="^([0-9]+)$"; // ^-start,$-end,+ positive closure,() grouping
Boolean f1=r1.matches(r2); // to ensure than roll no entered is only integer
int flag=0;
int flag1=0;
int flag2=0;
  if(txtRoll.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p1,"Enter Roll no","Information Incomplete",JOptionPane.ERROR_MESSAGE);
             flag2=1;
        }
          else if(pwdPass.getText().equals(s))   //to check empty password field
        {
             JOptionPane.showMessageDialog(p1,"Enter Password","Information Incomplete",JOptionPane.ERROR_MESSAGE);
               flag2=1;  
               
        }
         else if(txtName.getText().equals(s))   //to check empty password field
        {
             JOptionPane.showMessageDialog(p1,"Enter Name","Information Incomplete",JOptionPane.ERROR_MESSAGE);
               flag2=1;  
              
        }    
if(f && f1 && flag2==0)
{

         DBCursor cursor=dbc.find();
           
        pwdPass.selectAll();
      
       String roll = txtRoll.getText();
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
           
              String str=(String)obj.get("RollNo");
              String pwd=(String)obj.get("Password");
               String n=(String)obj.get("Name");
              if(txtRoll.getText().toString().equals(str) && pwdPass.getSelectedText().toString().equals(pwd) && txtName.getText().toString().equals(n) )
         {
                JOptionPane.showMessageDialog(p1,"login successful","login success",JOptionPane.INFORMATION_MESSAGE);
               Vector v=new Vector();
             v.add(txtRoll.getText());
                  v.add(txtName.getText());
                 new Test(v).setVisible(true);
               // t.genCode(roll);
               // this.dispose();
               
               
               
              this.setVisible(false);
                
                flag=1;
         }
              
   
    
        }
        
              
    
   
    }//GEN-LAST:event_btnLoginActionPerformed
else if(flag2==0)
{
JOptionPane.showMessageDialog(p1,"invalid roll no or name","login failed",JOptionPane.ERROR_MESSAGE);
txtRoll.setText("");
txtName.setText("");
pwdPass.setText("");
flag1=1;
}  
if(flag==0 && flag1==0)
   {
       JOptionPane.showMessageDialog(p1,"login unsuccessful","login failed",JOptionPane.ERROR_MESSAGE); 
         this.setVisible(false);
               new Student().setVisible(true);
       
   }
    
    
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      this.setVisible(false);
      new frmWelcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollActionPerformed

    private void pwdPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPassActionPerformed

    /**
   }  * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoll;
    // End of variables declaration//GEN-END:variables
}
