
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Color;
import java.awt.TextArea;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranoti
 */
public class Test extends javax.swing.JFrame {
    
      static String id="";    
      int count=0;
       
      
       // int f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15=0;
// initialisation of global variable

    /**
     * Creates new form Test
     */
    public Test(Vector v) {
        initComponents();
         this.lblRoll.setText((String)v.elementAt(0));
          this.lblName.setText((String)v.elementAt(1));
          //this.lblPName.setText((String)v.elementAt(2));
        //  this.lblGender.setText((String)v.elementAt(3));
         // this.lblDOB.setText((String)v.elementAt(4));
         // this.lblPassword.setText((String)v.elementAt(5));
    }

   

   Test() {
        initComponents();
       
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

     public void genCode(String roll)
     {
         lblRoll.setText(roll);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        P3 = new javax.swing.JPanel();
        lblQ = new javax.swing.JLabel();
        lblOpt = new javax.swing.JLabel();
        rdbA = new javax.swing.JRadioButton();
        rdbB = new javax.swing.JRadioButton();
        rdbC = new javax.swing.JRadioButton();
        rdbD = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        lblsr = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        P0 = new javax.swing.JPanel();
        lblTest = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        P2 = new javax.swing.JPanel();
        lblGender = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblI3 = new javax.swing.JLabel();
        btnok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRno = new javax.swing.JLabel();
        lblRoll = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 244, 202));
        jPanel1.setLayout(null);

        P3.setBackground(new java.awt.Color(230, 244, 202));
        P3.setLayout(null);
        P3.add(lblQ);
        lblQ.setBounds(70, 20, 460, 85);
        P3.add(lblOpt);
        lblOpt.setBounds(100, 100, 320, 38);

        buttonGroup1.add(rdbA);
        rdbA.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        rdbA.setText("A");
        P3.add(rdbA);
        rdbA.setBounds(80, 179, 35, 25);

        buttonGroup1.add(rdbB);
        rdbB.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        rdbB.setText("B");
        P3.add(rdbB);
        rdbB.setBounds(130, 180, 40, 25);

        buttonGroup1.add(rdbC);
        rdbC.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        rdbC.setText("C");
        P3.add(rdbC);
        rdbC.setBounds(80, 220, 40, 25);

        buttonGroup1.add(rdbD);
        rdbD.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        rdbD.setText("D");
        P3.add(rdbD);
        rdbD.setBounds(130, 220, 40, 25);

        btnSave.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        P3.add(btnSave);
        btnSave.setBounds(180, 200, 60, 30);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        P3.add(btn5);
        btn5.setBounds(282, 266, 39, 23);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        P3.add(btn4);
        btn4.setBounds(282, 237, 39, 23);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        P3.add(btn1);
        btn1.setBounds(282, 151, 39, 23);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        P3.add(btn2);
        btn2.setBounds(282, 179, 39, 23);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        P3.add(btn3);
        btn3.setBounds(282, 208, 39, 23);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        P3.add(btn6);
        btn6.setBounds(339, 151, 39, 23);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        P3.add(btn7);
        btn7.setBounds(339, 179, 39, 23);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        P3.add(btn8);
        btn8.setBounds(339, 208, 39, 23);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        P3.add(btn9);
        btn9.setBounds(339, 237, 39, 23);

        btn10.setText("10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        P3.add(btn10);
        btn10.setBounds(339, 266, 45, 23);

        btn11.setText("11");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        P3.add(btn11);
        btn11.setBounds(396, 151, 45, 23);

        btn12.setText("12");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        P3.add(btn12);
        btn12.setBounds(396, 179, 45, 23);

        btn13.setText("13");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        P3.add(btn13);
        btn13.setBounds(396, 208, 45, 23);

        btn14.setText("14");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        P3.add(btn14);
        btn14.setBounds(396, 237, 45, 23);

        btn15.setText("15");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        P3.add(btn15);
        btn15.setBounds(400, 270, 45, 23);

        lblsr.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblsr.setText("Sr");
        P3.add(lblsr);
        lblsr.setBounds(30, 30, 30, 43);

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        P3.add(btnSubmit);
        btnSubmit.setBounds(440, 340, 80, 30);

        jPanel1.add(P3);
        P3.setBounds(20, 170, 570, 390);

        P0.setBackground(new java.awt.Color(230, 244, 202));
        P0.setLayout(null);

        lblTest.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblTest.setText("Enter your subject ID");
        P0.add(lblTest);
        lblTest.setBounds(0, 50, 185, 27);

        txtSubject.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        P0.add(txtSubject);
        txtSubject.setBounds(190, 50, 60, 30);

        btnOK.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        P0.add(btnOK);
        btnOK.setBounds(100, 100, 60, 30);

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "S_id"
            }
        ));
        jScrollPane1.setViewportView(tblDetails);

        P0.add(jScrollPane1);
        jScrollPane1.setBounds(330, 30, 134, 60);

        jPanel1.add(P0);
        P0.setBounds(80, 10, 490, 150);

        P2.setBackground(new java.awt.Color(230, 244, 202));
        P2.setLayout(null);

        lblGender.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        lblGender.setText("1.YOU CANNOT CHANGE AN ANSWER TO A PARTICULAR QUESTION ONCE YOU CLICK ON SAVE ");
        P2.add(lblGender);
        lblGender.setBounds(24, 58, 550, 69);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel1.setText("INSTRUCTIONS");
        P2.add(jLabel1);
        jLabel1.setBounds(230, 20, 157, 32);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel2.setText(" 2.YOU CANNOT REVISIT A QUESTION ");
        P2.add(jLabel2);
        jLabel2.setBounds(24, 138, 274, 30);

        lblI3.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        lblI3.setText("3. YOUR TIME IS");
        P2.add(lblI3);
        lblI3.setBounds(24, 179, 134, 33);

        btnok.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        P2.add(btnok);
        btnok.setBounds(240, 313, 50, 40);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel3.setText("4. YOUR TEST BEGINS ONCE YOU SELECT THE SUBJECT ID");
        P2.add(jLabel3);
        jLabel3.setBounds(24, 230, 314, 32);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel5.setText("5. RED SAVE BUTTON MEANS YOUR ANSWER IS NOT SAVED!");
        P2.add(jLabel5);
        jLabel5.setBounds(24, 273, 370, 32);

        jPanel1.add(P2);
        P2.setBounds(620, 100, 590, 370);

        lblRno.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblRno.setText("Roll no.");
        jPanel1.add(lblRno);
        lblRno.setBounds(700, 10, 70, 36);
        jPanel1.add(lblRoll);
        lblRoll.setBounds(790, 10, 50, 27);

        lblN.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblN.setText("Name");
        jPanel1.add(lblN);
        lblN.setBounds(700, 50, 60, 29);
        jPanel1.add(lblName);
        lblName.setBounds(790, 50, 320, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
     // txtSubject.setText("");
        ConnectA ca=new ConnectA();
DBCollection dbca=ca.connecta();
        id=txtSubject.getText();      // id is global 
    P0.setVisible(false);
//    spncount.setValue(1000);
     final JPanel p2=new JPanel();
         final JOptionPane jo=new JOptionPane();
         int flag=0;
         int flag1=0;
    if(txtSubject.getText().toString().equals(""))
        {
             JOptionPane.showMessageDialog(p2,"Enter Valid Sujbect ID","Information Incomplete",JOptionPane.ERROR_MESSAGE);
               flag=1;
              P0.setVisible(false); // so that the panel disappears due to invalid input! 
              P3.setVisible(false);
               P0.setVisible(true); // and t reapperas here to enter again!
        }
    ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
 DBCursor cursor=dbcq.find();
 DBCursor cursor1=dbca.find();
 
         
          if(flag==0)   // subject id field is not null
          {
             while(cursor1.hasNext())             //to check if test is already given
           { 
                 
             DBObject obj1=cursor1.next();  //to search from Analysis
             String R=(String)obj1.get("RollNo");  //from the collection of Analysis
             String Id=(String)obj1.get("sub_id");
               //System.out.println(R);
               //System.out.println(Id);
             if(id.equals(Id)&& lblRoll.getText().equals(R)) //cursor stops at matching ID
             {
                 JOptionPane.showMessageDialog(p2,"Test given","Information Incomplete",JOptionPane.ERROR_MESSAGE);
                 flag1=1;
                 
             }
           
           }
                if(flag1==0)          //if test is not given
                {
           
           while(cursor.hasNext())
           {
            DBObject obj=cursor.next();     //to search from Questions
             
String ID=(String)obj.get("sub_id"); 
String srno=(String)obj.get("sr"); // from the collection of questions

if(ID.equals(id) && srno.equals("1")) //cursor stops at matching ID
{
             
             P3.setVisible(true);  // so the questions appear only if we have given valid sub id
                
            btnSave.setBackground(Color.red);  // red color to show that the question isnt saved!
           String q=(String)obj.get("q");
             String opt=(String)obj.get("opt");
             lblQ.setText(q);
         lblsr.setText("1");
             lblOpt.setText(opt);
             
             flag=2;
             break;
            
}


    }           
    
          }
     if(flag!=2 && flag1!=1) // no matching sub id   and if test is not given!
{    P0.setVisible(false); // so that the panel disappears due to invalid input! 
              P3.setVisible(false);
               P0.setVisible(true); // and panel reappears here to enter again!
     JOptionPane.showMessageDialog(p2,"Enter Valid Sujbect ID","Information Incomplete",JOptionPane.ERROR_MESSAGE);
      
     
   
}
    
          }

        

// TODO add your handling code here:
    }//GEN-LAST:event_btnOKActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
P0.setVisible(false);
P3.setVisible(false);    
P2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
          ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext()){

 DBObject obj=cursor.next();
  P3.setVisible(true);
String ID=(String)obj.get("sub_id");
String srno=(String)obj.get("sr");
if(ID.equals(id) && srno.equals("2")) //cursor stops at matching ID
   
{
       
        
  // DBObject obj1=dbcq.findOne(new BasicDBObject("sr",2),new BasicDBObject("sub_id",id) );
           String q=(String)obj.get("q");
             String opt=(String)obj.get("opt");
             lblQ.setText(q);
              lblsr.setText(srno);
             lblOpt.setText(opt);
           
           break;
  }

    }//GEN-LAST:event_btn2ActionPerformed
  /* if(!btnSave.isSelected())
   {
      System.out.println("abcd");
    btn2.setEnabled(false);
  } 
   else
   {System.out.println("xyz");
       btn2.setEnabled(true);
   } */
  btn2.setEnabled(false);
    }
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext()){

 DBObject obj=cursor.next();
  P3.setVisible(true);
String ID=(String)obj.get("sub_id");
String srno=(String)obj.get("sr");
if(ID.equals(id) && srno.equals("3")) //cursor stops at matching ID
   
{
           String q=(String)obj.get("q");
             String opt=(String)obj.get("opt");
             lblQ.setText(q);
              lblsr.setText(srno);
             lblOpt.setText(opt);
           break;
  }

  }                                  
btn3.setEnabled(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
 ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("4")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }   btn4.setEnabled(false);                                         // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("5")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }   btn5.setEnabled(false);                               // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
//btnSave.setBackground(Color.red);
 btnSave.setEnabled(true);
   buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("1")) //cursor stops at matching ID
   
             {
                   
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblsr.setText(srno);
                  lblQ.setText(q);
                   lblOpt.setText(opt);
                  break;
          }

  }
  if(!btnSave.isEnabled())
  {
  btn1.setEnabled(false);
  }// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("6")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                   lblsr.setText(srno);
                  lblQ.setText(q);
                   lblOpt.setText(opt);
                  break;
          }

       }   btn6.setEnabled(false);                               // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("7")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }     btn7.setEnabled(false);                             // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setEnabled(true);
btnSave.setBackground(Color.red);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("8")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }     btn8.setEnabled(false);                             // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("9")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }    btn9.setEnabled(false);                              // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("10")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }  btn10.setEnabled(false);                                // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("11")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }     btn11.setEnabled(false);                             // TODO add your handling code here:
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("12")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }     btn12.setEnabled(false);                             // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("13")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }  btn13.setEnabled(false);                                // TODO add your handling code here:
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("14")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }    btn14.setEnabled(false);                              // TODO add your handling code here:
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();
btnSave.setBackground(Color.red);
btnSave.setEnabled(true);
buttonGroup1.clearSelection();
  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
    String srno=(String)obj.get("sr");
       if(ID.equals(id) && srno.equals("15")) //cursor stops at matching ID
   
             {
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  lblQ.setText(q);
                   lblsr.setText(srno);
                   lblOpt.setText(opt);
                  break;
          }

       }   btn15.setEnabled(false);                               // TODO add your handling code here:
    }//GEN-LAST:event_btn15ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

ConnectQ cq=new ConnectQ();
DBCollection dbcq=cq.connectq();
DBCursor cursor=dbcq.find();

  while(cursor.hasNext())
  {

    DBObject obj=cursor.next();
    P3.setVisible(true);
    String ID=(String)obj.get("sub_id");
   String srno=(String)obj.get("sr");
   //String srn=""+srno;
   //String srno="1";
       if(ID.equals(id) && lblsr.getText().equals(srno)) //cursor stops at matching ID
   
             {
                 
                  String q=(String)obj.get("q");
                  String opt=(String)obj.get("opt");
                  String corr=(String)obj.get("corr");
                  lblQ.setText(q);
                   lblOpt.setText(opt);
                   String s=lblsr.getText();
                       
                  if(rdbA.isSelected())
                  {           String a=rdbA.getText();
                                 if(a.equals(corr))
                                 {
                                     count=count+2;
                                    
                                  }
                           btnSave.setEnabled(false); //so that he cant make the ans for this Q again and increase his marks
                  }
                  else if(rdbB.isSelected())
                  {           String a=rdbB.getText();
                                 if(a.equals(corr))
                                 {
                                     count=count+2;
                                    
                                  }
                                 btnSave.setEnabled(false);
                  }
                  else if(rdbC.isSelected())
                  {           String a=rdbC.getText();
                                 if(a.equals(corr))
                                 {
                                     count=count+2;
                                     
                                  }
                                btnSave.setEnabled(false);
                  }
                  else if(rdbD.isSelected())
                  {           String a=rdbD.getText();
                                 if(a.equals(corr))
                                 {
                                     count=count+2;
                                      
                                  }
                                btnSave.setEnabled(false);
                  }
                  
          }

       }                          
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
                ConnectA a=new ConnectA();
                DBCollection db=a.connecta();
                 BasicDBObject bdb= new BasicDBObject();
                 Connect c=new Connect();
                DBCollection db1=c.connect();
                final JPanel p2=new JPanel();
final JOptionPane jo=new JOptionPane();
                // BasicDBObject bdb2= new BasicDBObject();
                 
                 
          /*         DBCursor cursor=db1.find();
                 String rno=lblRoll.getText();
                 while(cursor.hasNext()){
            DBObject obj=cursor.next();
             String str=(String)obj.get("RollNo");
                if(rno.equals(str)) */
                //{
                  // BasicDBObject bdb2= new BasicDBObject().append("RollNo", rno); 
                   
                   bdb.put("Marks",count);
                   
         bdb.put("sub_id",id);           
        bdb.put("RollNo",lblRoll.getText());
        bdb.put("Name",lblName.getText());
      //  bdb.put("DOB",lblDOB.getText());
       // bdb.put("Gender",lblGender.getText());
       // bdb.put("Parent's Name",lblPName.getText());
       //  bdb.put("Password",lblPassword.getText());
                    db.insert(bdb);
                   Vector v=new Vector();
             v.add(lblRoll.getText());
             //new PdfCreator(v).setVisible(true);
                 //}
       // System.out.println(count); 
                // TODO add your handling code here:
                 JOptionPane.showMessageDialog(p2,"Congratulations you have scored  "+count+"  marks","Result",JOptionPane.INFORMATION_MESSAGE); 
                this.setVisible(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed

P0.setVisible(true);
ConnectSub csb=new ConnectSub();
DBCollection dbcsub=csb.connectsub();
BasicDBObject bdb= new BasicDBObject();
   String[] colNames={"Name","S_id"};
     P2.setVisible(false);  
       
//TextArea ta=new TextArea(10,1);
 DefaultTableModel dtm=new DefaultTableModel(colNames,0);
  DBCursor cursor=dbcsub.find();
        while(cursor.hasNext()){
            DBObject obj=cursor.next();
            String sub=(String)obj.get("Name");
            String sub_id=(String)obj.get("S_id");
           dtm.addRow(new Object[]{sub,sub_id});
         tblDetails.setModel(dtm);
         P3.setVisible(false);
      
            
        }  
        
        btn1.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Test().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P0;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnok;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblI3;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOpt;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblRno;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblsr;
    private javax.swing.JRadioButton rdbA;
    private javax.swing.JRadioButton rdbB;
    private javax.swing.JRadioButton rdbC;
    private javax.swing.JRadioButton rdbD;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
